version: '3.7'

services:
  app:
    image: test/test:latest
    ports: 
      - 8080:80
    working_dir: /var/www/html
    volumes: 
      - ./:/var/www/html
    links:
      - db
    depends_on:
      - db
  
  db:
    image: mysql:latest
    environment: 
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
    links:
      - db
    depends_on:
      - db